version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: lab_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:7
    container_name: lab_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  etl:
    build: .
    container_name: lab_etl
    env_file:
      - .env

volumes:
  postgres_data:
  mongo_data: